### ISSUE TITLE
Control Automático

### ISSUE THREAD

**Issue by Hitomiblood** [santix234/Universidad#5]
- [ ] Realizar las lecturas recomendadas, para recordar como diseñar un control PID.

**Comment by santix234** [comment]
> * [ ]  Exposición de 10 mins en base a la lectura

**Comment by santix234** [comment]
> * [x]  Exposición de 10 mins en base a la lectura

**Comment by santix234** [comment]
> * [x]  Exposición de 10 mins en base a la  @santix234

**Comment by Hitomiblood** [comment]
> * [ ]  Exposición de 10 mins en base a la lectura **_Santiago_** - Miguel

**Comment by santix234** [comment]
update
